# Generated by Django 2.1.5 on 2019-02-11 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(default='', max_length=140)),
                ('author', models.CharField(default='', max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(default='', max_length=140)),
                ('country', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(default='', max_length=140)),
                ('author', models.CharField(default='', max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(default='', max_length=140)),
                ('country', models.CharField(default='', max_length=140)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=5)),
                ('imageFile', models.ImageField(null=True, upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(default='', max_length=140)),
                ('author', models.CharField(default='', max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(default='', max_length=140)),
                ('country', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
