# Generated by Django 2.1.5 on 2019-02-10 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='audio',
            name='city',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='audio',
            name='country',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='audio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='image',
            name='city',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='image',
            name='country',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='video',
            name='city',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
    ]
